version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    volumes:
      - ./:/app
      - ./output:/app/output
    restart: always
    depends_on:
      - server
    networks:
      - appnet

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
